export const ACTIVITIES_SET = 'ACTIVITIES_SET'
export const URL_RECEIVED = 'URL_RECEIVED'
export const URL_RESET = 'URL_RESET'
export const FAV_SET = 'FAV_SET'
export const ACTIVITY_RUN = 'ACTIVITY_RUN'
export const COPY_TO_CLIPBOARD = 'COPY_TO_CLIPBOARD'
