export const ACTIVITIES_GET = 'ACTIVITIES_GET'
export const ACTIVITIES_SET = 'ACTIVITIES_SET'
export const PICKER_BLUR = 'PICKER_BLUR'
export const URL_RECEIVED = 'URL_RECEIVED'
export const FAV_SET = 'FAV_SET'
export const FAV_GET = 'GET_FAV'
export const ACTIVITY_RUN = 'ACTIVITY_RUN'
