export const APP_LOADED = 'APP_LOADED'
export const BROWSERS_SET = 'BROWSERS_SET'
export const BROWSER_RUN = 'BROWSER_RUN'
export const COPY_TO_CLIPBOARD = 'COPY_TO_CLIPBOARD'
export const FAV_SET = 'FAV_SET'
export const URL_RECEIVED = 'URL_RECEIVED'
