export const BROWSERS_SCANNED = 'BROWSERS_SCANNED'
export const URL_HISTORY_CHANGED = 'URL_HISTORY_CHANGED'
export const APP_VERSION = 'APP_VERSION'
export const FAVOURITE_CHANGED = 'FAVOURITE_CHANGED'
